version: '3'
services:
  gg-mysql:
    container_name: gg-mysql
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: gg
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: root
    ports:
      - "3306:3306"
    restart: always
    network_mode: host

  app:
    image: bankgg
    restart: always
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - gg-mysql
